### PR TITLE
feat: probe endpoint /status

### PR DESCRIPTION
**Pull request by dnplkndll**
adding a probe endpoint
bump
gitlab build ci (server)

### CODE REVIEW

**Comment by sbidoul** [comment]
@dnplkndll thanks for the contrib.

Could you do the 0.12.6 Dockerfile and the status endpoints in separate PRs ?
Note the Dockerfiles were modified/fixed in #12.

Regarding CI, I don't have travis credits but I made the build and publish workflow to ghcr.io.

I'll see if I can move the tests to GitHub actions too.

**Comment by dnplkndll** [comment]
fixed up

reasoning is we use the autodevops to build and review/release. I have had to put in a few updates. but the resulting helm chart will now allow an odoo with workers(cron/queue) and then reporting service I was thinking. 

https://gitlab.com/gitlab-org/cluster-integration/auto-deploy-image/-/merge_requests/259

I was a little curious on any sizing recommendations?

**Comment by sbidoul** [comment]
Memory and CPU requirements heavily depend on the actual reports being generated, so you'll need to experiment with your workloads.

**Comment by dnplkndll** [comment]
> Memory and CPU requirements heavily depend on the actual reports being generated, so you'll need to experiment with your workloads.

well guess I should do worker hpa feature next!

**Comment by jappi00** [comment]
Any updates on this? Would be nice for our docker compose setups

**Comment by sbidoul** [comment]
I had lost track for this. Thanks for the contrib. I cherry-picked it and added a test in #20.

**Pull request closed without merging**
