### PR TITLE
[DOC] Updated the "Run the client" section and added an example using `go run`

### PR DESCRIPTION
**Pull request by alexandregaldeano**

### CODE REVIEW

**Review by petrus-v — APPROVED** [review]

**Comment by sbidoul** [comment]
What's wrong with the python client example?

**Comment by alexandregaldeano** [comment]
When I first tried it, it didn't work. I thought something was wrong with the Python implementation, so I updated the README (so I don't forget later). It was a couple of days ago, and I now realized that the issues I first had had nothing to do with Python.

So, I can either add the Go example in complement to the Python example, or we can just close this PR. What's your preference?

Sorry about that :(

**Comment by sbidoul** [comment]
But the go example is just above, no?

**Comment by alexandregaldeano** [comment]
Using the compiled binary yes, but not using the `go run` command, I don't know Go enough to know what are the actual implications of using one versus the other.

**Comment by sbidoul** [comment]
Ah I see. I don't know all the implications either but I guess adding a additional `go run` example is fine for easier testing.

**Comment by alexandregaldeano** [comment]
Ok, I put back the Python example. I also reorganized this section a little bit, what do you think?
image

**Comment by alexandregaldeano** [comment]
I also renamed the commit and the PR

**Comment by sbidoul** [comment]
Nice, thanks!

**Pull request merged**
