### PR TITLE
Use bionic build for main docker image and add an alternative docker image for older odoo projects

### PR DESCRIPTION
**Pull request by nilshamerlinck**
PS: great idea!

### CODE REVIEW

**Comment by sbidoul** [comment]
Thanks for the contrib.

BTW, I'm using this project to teach myself some golang, I'll soon push a go version of the server.

**Comment by sbidoul** [comment]
@nilshamerlinck do you think I should tag the docker image `0.12.1-latest` or `0.12.1.3-latest`?

**Comment by nilshamerlinck** [comment]
@sbidoul I would vote for the most explicit, even if the only differences between the 0.12.1.x sub-versions are openssl and libpng upgrades

**Comment by sbidoul** [comment]
@nilshamerlinck I created both tags. Build in progress at docker hub.

**Pull request merged**
